before_script:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -q
  - sudo apt-get install -y gcc-arm-none-eabi=4-8-2014q2-0trusty10 

language: cpp

script:
  - make clean
  - make
